# Generated by Django 3.1.7 on 2021-04-02 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_institute', models.BooleanField(default=False)),
                ('is_department', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=2000)),
                ('poster', models.FileField(upload_to=events.models.poster_upload)),
                ('registration_fee', models.IntegerField()),
                ('payment_no', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.council')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('division', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('is_gs', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to=events.models.student_photo_upload)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.council')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_hod', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to=events.models.staff_photo_upload)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.council')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EventWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='staff_approved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.staff'),
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.council')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.student')),
            ],
        ),
        migrations.AddField(
            model_name='council',
            name='dept',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.department'),
        ),
    ]
