# Generated by Django 3.1.7 on 2021-04-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_staffidmap_studentidmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='council',
            name='dept',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.department'),
        ),
    ]
