# Generated by Django 3.1.7 on 2021-04-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210403_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='payment_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.IntegerField(default=0),
        ),
    ]
