# Generated by Django 3.1.7 on 2021-04-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210403_1130'),
        ('events', '0003_auto_20210403_0939'),
    ]

    operations = [
    ]
