# Generated by Django 3.1.7 on 2021-04-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_merge_20210403_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('accept_requests', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approve_time', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('belongsTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.council')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.userroles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
