# Generated by Django 3.1.7 on 2021-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rolerequests_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequests',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
