# Generated by Django 3.1.7 on 2021-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210403_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequests',
            name='approve_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
